"""Load generated FHIR datasets into a relational SQLite database.

This script reads the CSV files generated by `extract_data.py` and the
optional clinical NLP datasets generated by `extract_clinical_entities.py`,
then loads them into a local SQLite database with explicit schemas and
indexes for fast querying.
"""

import os
import sqlite3
import sys

import pandas as pd

# -----------------
# Configuration
# -----------------
DATA_DIR = "datasets"
DB_PATH = os.path.join(DATA_DIR, "fhir_knowledge_base.db")


def check_csv_files_exist() -> bool:
    """Verify that the core ETL CSV files have been generated."""
    required_files = ["patients.csv", "conditions.csv", "labs.csv", "medications.csv"]
    for filename in required_files:
        if not os.path.exists(os.path.join(DATA_DIR, filename)):
            print(f"Error: Required file '{filename}' not found in '{DATA_DIR}/'.")
            return False
    return True


def setup_database(conn: sqlite3.Connection):
    """Create explicit schemas with primary and foreign keys."""
    cursor = conn.cursor()

    # Drop tables if they exist for idempotency
    cursor.execute("DROP TABLE IF EXISTS clinical_entities")
    cursor.execute("DROP TABLE IF EXISTS clinical_notes")
    cursor.execute("DROP TABLE IF EXISTS medications")
    cursor.execute("DROP TABLE IF EXISTS labs")
    cursor.execute("DROP TABLE IF EXISTS conditions")
    cursor.execute("DROP TABLE IF EXISTS patients")

    # 1. Patients Table
    cursor.execute("""
        CREATE TABLE patients (
            patient_id TEXT PRIMARY KEY,
            first_name TEXT,
            last_name TEXT,
            gender TEXT,
            race TEXT,
            ethnicity TEXT,
            marital_status TEXT,
            city TEXT,
            state TEXT,
            country TEXT,
            age INTEGER
        )
    """)

    # 2. Conditions Table
    cursor.execute("""
        CREATE TABLE conditions (
            patient_id TEXT,
            condition TEXT,
            code TEXT,
            system TEXT,
            onset_date TEXT,
            abatement_date TEXT,
            clinical_status TEXT,
            FOREIGN KEY (patient_id) REFERENCES patients (patient_id)
        )
    """)

    # 3. Labs Table
    cursor.execute("""
        CREATE TABLE labs (
            patient_id TEXT,
            observation TEXT,
            code TEXT,
            system TEXT,
            value REAL,
            unit TEXT,
            date TEXT,
            category TEXT,
            FOREIGN KEY (patient_id) REFERENCES patients (patient_id)
        )
    """)

    # 4. Medications Table
    cursor.execute("""
        CREATE TABLE medications (
            patient_id TEXT,
            medication TEXT,
            code TEXT,
            system TEXT,
            start_date TEXT,
            end_date TEXT,
            status TEXT,
            FOREIGN KEY (patient_id) REFERENCES patients (patient_id)
        )
    """)

    # 5. Clinical Notes Table
    cursor.execute("""
        CREATE TABLE clinical_notes (
            note_id TEXT PRIMARY KEY,
            patient_id TEXT,
            bundle_file TEXT,
            resource_type TEXT,
            resource_id TEXT,
            note_source TEXT,
            note_text TEXT,
            FOREIGN KEY (patient_id) REFERENCES patients (patient_id)
        )
    """)

    # 6. Clinical Entities Table
    cursor.execute("""
        CREATE TABLE clinical_entities (
            entity_id TEXT PRIMARY KEY,
            patient_id TEXT,
            bundle_file TEXT,
            resource_type TEXT,
            resource_id TEXT,
            note_id TEXT,
            note_source TEXT,
            note_text TEXT,
            entity_text TEXT,
            entity_label TEXT,
            assertion TEXT,
            is_negated INTEGER,
            is_uncertain INTEGER,
            is_historical INTEGER,
            is_family INTEGER,
            start_char INTEGER,
            end_char INTEGER,
            FOREIGN KEY (note_id) REFERENCES clinical_notes (note_id),
            FOREIGN KEY (patient_id) REFERENCES patients (patient_id)
        )
    """)

    conn.commit()


def create_indexes(conn: sqlite3.Connection):
    """Add indexes to speed up foreign key JOIN operations."""
    cursor = conn.cursor()
    cursor.execute("CREATE INDEX idx_conditions_patient_id ON conditions(patient_id)")
    cursor.execute("CREATE INDEX idx_labs_patient_id ON labs(patient_id)")
    cursor.execute("CREATE INDEX idx_medications_patient_id ON medications(patient_id)")
    cursor.execute("CREATE INDEX idx_clinical_notes_patient_id ON clinical_notes(patient_id)")
    cursor.execute("CREATE INDEX idx_clinical_notes_resource ON clinical_notes(resource_type, resource_id)")
    cursor.execute("CREATE INDEX idx_clinical_entities_patient_id ON clinical_entities(patient_id)")
    cursor.execute("CREATE INDEX idx_clinical_entities_note_id ON clinical_entities(note_id)")
    cursor.execute("CREATE INDEX idx_clinical_entities_label ON clinical_entities(entity_label)")
    conn.commit()


def main():
    """Main entry point: validate files, set up DB, and load data."""
    print("Initializing FHIR Knowledge Base...")

    # 1. Validate environment
    if not os.path.isdir(DATA_DIR):
        print(f"Error: Directory '{DATA_DIR}' not found.")
        sys.exit(1)

    if not check_csv_files_exist():
        print("Please run 'python extract_data.py' first to generate datasets.")
        sys.exit(1)

    # 2. Connect to SQLite
    print(f"Connecting to database: {DB_PATH}")
    conn = sqlite3.connect(DB_PATH)

    try:
        # 3. Setup explicitly defined schema
        print("Setting up table schemas...")
        setup_database(conn)

        # 4. Read CSVs and insert data using pandas
        print("Loading patients...")
        patients_df = pd.read_csv(os.path.join(DATA_DIR, "patients.csv"))
        patients_df.to_sql("patients", conn, if_exists="append", index=False)

        print("Loading conditions...")
        conditions_df = pd.read_csv(os.path.join(DATA_DIR, "conditions.csv"))
        conditions_df.to_sql("conditions", conn, if_exists="append", index=False)

        print("Loading labs...")
        labs_df = pd.read_csv(os.path.join(DATA_DIR, "labs.csv"))
        labs_df.to_sql("labs", conn, if_exists="append", index=False)

        print("Loading medications...")
        medications_df = pd.read_csv(os.path.join(DATA_DIR, "medications.csv"))
        medications_df.to_sql("medications", conn, if_exists="append", index=False)

        clinical_notes_path = os.path.join(DATA_DIR, "clinical_notes.csv")
        if os.path.exists(clinical_notes_path):
            print("Loading clinical notes...")
            clinical_notes_df = pd.read_csv(clinical_notes_path)
            clinical_notes_df.to_sql("clinical_notes", conn, if_exists="append", index=False)
        else:
            print("Clinical notes CSV not found; skipping note table load.")

        clinical_entities_path = os.path.join(DATA_DIR, "clinical_entities.csv")
        if os.path.exists(clinical_entities_path):
            print("Loading clinical entities...")
            clinical_entities_df = pd.read_csv(clinical_entities_path)
            clinical_entities_df.to_sql("clinical_entities", conn, if_exists="append", index=False)
        else:
            print("Clinical entities CSV not found; skipping NLP table load.")

        # 5. Optimize queries with Indexes
        print("Creating indexes...")
        create_indexes(conn)

        # 6. Verify row counts
        print("\nDatabase load complete. Summary:")
        cursor = conn.cursor()
        table_labels = {
            "patients": "Patients",
            "conditions": "Conditions",
            "labs": "Labs",
            "medications": "Medications",
            "clinical_notes": "Clinical notes",
            "clinical_entities": "Clinical entities",
        }
        for table, label in table_labels.items():
            cursor.execute(f"SELECT COUNT(*) FROM {table}")
            count = cursor.fetchone()[0]
            print(f"  {label}: {count} rows")

        print(f"\nKnowledge base ready for querying at '{DB_PATH}'")

    finally:
        conn.close()


if __name__ == "__main__":
    main()
